'use strict'

// Matrix Commands.
exports.MATRIX_TRANSLATE = 0xC0 // 192
exports.MATRIX_SCALE_ORIGIN = 0xC1 // 193
exports.MATRIX_ROTATE_ORIGIN = 0xC2 // 194
exports.MATRIX_SCALE = 0xC4 // 196
exports.MATRIX_ROTATE = 0xC5 // 197
exports.MATRIX_RESET = 0xC3 // 195

exports.OPTION_MAX_STITCH_LENGTH = 0xD5
exports.OPTION_MAX_JUMP_LENGTH = 0xD6
exports.OPTION_EXPLICIT_TRIM = 0xD7
exports.OPTION_IMPLICIT_TRIM = 0xD8

exports.CONTINGENCY_TIE_ON_NONE = 0xD3
exports.CONTINGENCY_TIE_ON_THREE_SMALL = 0xD1

exports.CONTINGENCY_TIE_OFF_NONE = 0xD4
exports.CONTINGENCY_TIE_OFF_THREE_SMALL = 0xD2

exports.CONTINGENCY_LONG_STITCH_NONE = 0xF0
exports.CONTINGENCY_LONG_STITCH_JUMP_NEEDLE = 0xF1
exports.CONTINGENCY_LONG_STITCH_SEW_TO = 0xF2

exports.CONTINGENCY_SEQUIN_UTILIZE = 0xF5
exports.CONTINGENCY_SEQUIN_JUMP = 0xF6
exports.CONTINGENCY_SEQUIN_STITCH = 0xF7
exports.CONTINGENCY_SEQUIN_REMOVE = 0xF8
